plugins {
    id 'com.android.application'
}

android {
    namespace "com.hmz64.flytomoon"
    compileSdk 34
    ndkVersion "26.1.10909125"

    defaultConfig {
        applicationId "com.hmz64.flytomoon"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
                arguments "-DANDROID_STL=c++_shared"
                abiFilters 'arm64-v8a'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1+"
        }
    }

    buildTypes {
        debug {}
        release {
            minifyEnabled false
        }
    }
}
